name: context-classifier
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - aiohttp=3.7.4
  - async-timeout=3.0.1
  - attrs=21.2.0
  - boto=2.49.0
  - boto3=1.17.69
  - botocore=1.20.69
  - brotlipy=0.7.0
  - bz2file=0.98
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cachetools=4.2.2
  - catalogue=2.0.4
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - click=7.1.2
  - colorama=0.4.4
  - cryptography=3.4.7
  - cymem=2.0.5
  - cython-blis=0.7.4
  - dataclasses=0.8
  - google-api-core=1.26.3
  - google-auth=1.30.0
  - google-cloud-core=1.5.0
  - google-cloud-storage=1.19.0
  - google-crc32c=1.1.2
  - google-resumable-media=1.2.0
  - googleapis-common-protos=1.53.0
  - grpcio=1.37.1
  - idna=2.10
  - jinja2=2.11.3
  - jmespath=0.10.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcrc32c=1.1.1
  - libcxx=11.1.0
  - libffi=3.3
#  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.15
  - libprotobuf=3.16.0
  - llvm-openmp=11.1.0
  - markupsafe=1.1.1
  - multidict=5.1.0
  - murmurhash=1.0.5
  - ncurses=6.2
  - numpy=1.20.2
  - openssl=1.1.1k
  - packaging=20.9
  - pathy=0.5.2
  - preshed=3.0.5
  - protobuf=3.16.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pydantic=1.7.3
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.9.4
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2021.1
  - readline=8.1
  - requests=2.25.1
  - rsa=4.7.2
  - s3transfer=0.4.2
  - shellingham=1.4.0
  - six=1.16.0
  - smart_open=2.2.1
  - spacy=3.0.6
  - spacy-legacy=3.0.5
  - sqlite=3.35.4
  - srsly=2.4.1
  - thinc=8.0.3
  - tk=8.6.10
  - tqdm=4.60.0
  - typer=0.3.2
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzdata=2020f
  - urllib3=1.26.4
  - wasabi=0.8.2
  - wheel=0.36.2
  - xz=5.2.5
  - yarl=1.6.3
  - zlib=1.2.11
  - pip:
      - joblib==1.0.1
      - pip==21.1.1
      - pyyaml==5.4.1
      - scikit-learn==0.24.2
      - scipy==1.6.3
      - setuptools==56.2.0
      - sklearn==0.0
      - threadpoolctl==2.1.0
